<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Contains a precompiled binary file with IP location data for all countries in class C from IP2Location LITE.</Description>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>symbols.nupkg</SymbolPackageFormat>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Company>OmegaHood LLC</Company>
    <Copyright>© OmegaHood LLC. All rights reserved.</Copyright>
    <PackageIcon>VpnHood.png</PackageIcon>
    <PackageProjectUrl>https://github.com/vpnhood/VpnHood.AppLib.Assets.IpLocations</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vpnhood/VpnHood.AppLib.Assets.IpLocations</RepositoryUrl>
    <Version>7.0.746</Version>
    <FileVersion>$([System.DateTime]::Now.ToString("yyyy.M.d.HHmm"))</FileVersion>
    <PackageTags>IP Geolocation, IP2Location, VPN, Country Detection</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\VpnHood.png" Link="Resources\VpnHood.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\LICENSE" Link="Licenses\LICENSE">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Link="Licenses\README.md">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <SubType>Designer</SubType>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>